language: generic
dist: xenial
env:
 global:
# These parameters should match the parameters for build tools and sdk versions in the gradle file
 - ANDROID_BUILD_TOOLS=28.0.3 # should match gradle
 - ADB_INSTALL_TIMEOUT=5 # minutes
 - ANDROID_API=28 # api is same as gradle file
 - SDK_TOOLS=4333796 # 26.1.1
 - ANDROID_HOME=~/android-sdk
 matrix:
 - EMULATOR_API=21
 - EMULATOR_API=22
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - sudo apt-get -y update && sudo apt-get -y install openjdk8
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-$SDK_TOOLS.zip" -O android-sdk-tools.zip && unzip -q android-sdk-tools.zip -d "$ANDROID_HOME" && rm android-sdk-tools.zip && PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - mkdir -p ~/.android && touch ~/.android/repositories.cfg
  - yes | sdkmanager --licenses > /dev/null
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -15
  - sdkmanager "build-tools;$ANDROID_BUILD_TOOLS" "platforms;android-$ANDROID_API" > /dev/null
  - sdkmanager "system-images;android-$EMULATOR_API;google_apis;armeabi-v7a" > /dev/null
  - sdkmanager --list | head -15
  - sdkmanager "extras;google;m2repository" "extras;android;m2repository" "add-ons;addon-google_apis-google-19" > /dev/null
  - sdkmanager --list | head -15
  - echo no | avdmanager create avd -n test -k "system-images;android-$EMULATOR_API;google_apis;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
  - scripts/android-wait-for-emulator.sh
  - adb shell input keyevent 82

addons:
  srcclr: true
script:
  - ./gradlew cleanAllModules
  - ./gradlew testAllModulesTravis
  - if [[ -n $TRAVIS_TAG ]]; then ./gradlew ship; fi

# Integration tests need to run first to reset the PR build status to pending
stages:
  - name: 'Integration tests'
    if: type = pull_requesta
  - name: 'Test'

jobs:
  include:
    - stage: 'Integration tests'
      name: 'Integration tests'
      env:
        - SDK=android
        - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
      cache: false
      language: minimal
      before_install: skip
      install: skip
      before_script:
        - mkdir $HOME/travisci-tools && pushd $HOME/travisci-tools && git init && git pull https://$CI_USER_TOKEN@github.com/optimizely/travisci-tools.git && popd
      script:
        - "$HOME/travisci-tools/fsc-trigger/trigger_fullstack-sdk-compat.sh"
      after_success: travis_terminate 0
