language: generic
dist: xenial
env:
 global:
# These parameters should match the parameters for build tools and sdk versions in the gradle file
 - ANDROID_BUILD_TOOLS=28.0.3 # should match gradle
 - ADB_INSTALL_TIMEOUT=5 # minutes
 - ANDROID_API=28 # api is same as gradle file
 - SDK_TOOLS=4333796 # 26.1.1
 - ANDROID_HOME=~/android-sdk
 - JAVA_HOME=/usr/lib/jvm/jdk1.8.0_211
 matrix:
 - EMULATOR_API=21
 - EMULATOR_API=22
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - scripts/install_awscli.sh
  - scripts/install_java.sh
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - scripts/install_android.sh

addons:
  srcclr: true
script:
  - ./gradlew cleanAllModules
  - ./gradlew testAllModulesTravis
  - if [[ -n $TRAVIS_TAG ]]; then ./gradlew ship; fi

# Integration tests need to run first to reset the PR build status to pending
stages:
  - name: 'Integration tests'
    if: type = pull_requesta
  - name: 'Test'

jobs:
  include:
    - stage: 'Integration tests'
      name: 'Integration tests'
      env:
        - SDK=android
        - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
      cache: false
      language: minimal
      before_install: skip
      install: skip
      before_script:
        - mkdir $HOME/travisci-tools && pushd $HOME/travisci-tools && git init && git pull https://$CI_USER_TOKEN@github.com/optimizely/travisci-tools.git && popd
      script:
        - "$HOME/travisci-tools/fsc-trigger/trigger_fullstack-sdk-compat.sh"
      after_success: travis_terminate 0
